#! /bin/bash
echo "Varying Lamdba for sarsa lambda"
python3 run_sarsa_lambda.py --lam 0.8
python3 run_sarsa_lambda.py --lam 0.8
python3 run_sarsa_lambda.py --lam 0.8
python3 run_sarsa_lambda.py --lam 0.8
python3 run_sarsa_lambda.py --lam 0.85
python3 run_sarsa_lambda.py --lam 0.85
python3 run_sarsa_lambda.py --lam 0.85
python3 run_sarsa_lambda.py --lam 0.85
python3 run_sarsa_lambda.py --lam 0.9
python3 run_sarsa_lambda.py --lam 0.9
python3 run_sarsa_lambda.py --lam 0.9
python3 run_sarsa_lambda.py --lam 0.9
python3 run_sarsa_lambda.py --lam 0.92
python3 run_sarsa_lambda.py --lam 0.92
python3 run_sarsa_lambda.py --lam 0.92
python3 run_sarsa_lambda.py --lam 0.92
python3 run_sarsa_lambda.py --lam 0.95
python3 run_sarsa_lambda.py --lam 0.95
python3 run_sarsa_lambda.py --lam 0.95
python3 run_sarsa_lambda.py --lam 0.95
python3 run_sarsa_lambda.py --lam 0.98
python3 run_sarsa_lambda.py --lam 0.98
python3 run_sarsa_lambda.py --lam 0.98
python3 run_sarsa_lambda.py --lam 0.98
python3 run_sarsa_lambda.py --lam 0.99
python3 run_sarsa_lambda.py --lam 0.99
python3 run_sarsa_lambda.py --lam 0.99
python3 run_sarsa_lambda.py --lam 0.99
